version: '3'
services:
  mysql:
    image: mysql:8
    container_name: quartz_mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-quartz-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-quartz
      - MYSQL_DATABASE=quartz-data

volumes:
  mysql-quartz-data:
